// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

var TableNames = struct {
	Categories         string
	GorpMigrations     string
	ProductCategoryMap string
	ProductVersions    string
	Products           string
	Stock              string
	Transactions       string
	UserAuths          string
	Users              string
}{
	Categories:         "categories",
	GorpMigrations:     "gorp_migrations",
	ProductCategoryMap: "product_category_map",
	ProductVersions:    "product_versions",
	Products:           "products",
	Stock:              "stock",
	Transactions:       "transactions",
	UserAuths:          "user_auths",
	Users:              "users",
}
